# Numpy

# Importing

In [1]:
import numpy as np

#Numpy Array vs Normal Array

1. Similar datatype

Numpy array consists of similar datatypes only but normal lists in python may have different datatyes in it. Secondly if a different data type is forced in numpy array then it might just change the data types of all of the elements of the array

In [21]:
numpy_array = np.array([1, 2, 3, 4, 5, True, False]) # True gets changed into 1 and False will change into 0
print(numpy_array)
numpy_array = np.array([1, 2, 3, 4, 5, 5.43]) # Introducing a decimal value get all the other number to be changed into decimal
print(numpy_array)
numpy_array = np.array([1, 2, 3, 4, 5, "Naji"]) # Introducing a string value get all the other number to be changed into string
print(numpy_array)
numpy_array = np.array([1, 2, 3, 4, 5, {"naji": 123}]) # Introducing a dictionary value will make the it appear at the last
print(numpy_array)
#List cannot be added in the end this will result in an error
# numpy_array = np.array([1, 2, 3, 4, 5, [6, 7]])
# print(numpy_array)
#Touple cannot be added in the end this will result in an error
# numpy_array = np.array([1, 2, 3, 4, 5, (6, 7)])
# print(numpy_array)

[1 2 3 4 5 1 0]
[1.   2.   3.   4.   5.   5.43]
['1' '2' '3' '4' '5' 'Naji']
[1 2 3 4 5 {'naji': 123}]


2. Mathematical operation

Only the multiplication operation in numpy array and python list will result it with every element being mulriplied with 2 else any other operation is not pissible. If subtration, dicision and addition is done in normal python list it results in an error. It is solved by using a for loop. But for numpy array all the other operatio will result in it being every element being multiplied with the operation dont to it

In [42]:
python_list = [1, 2, 3, 4 ,5]
numpy_array = np.array([1, 2, 3, 4 ,5])

# Multiplying python_list with 2 results in just the array being duplicated
print("Python List: ", python_list * 2)
# Multiplying numpy_array with 2 results in with every element being multiplyed by 2
print("Numpy array: ", numpy_array * 2)

# Addition in not possible in python_list. The following code will result in error
# print(python_list + 2)
# In order to all every element use a for loop
print("Python List: ")
for number in python_list:
  print(number + 2, end = " ")
print()
# Addition in numpy_array will make every element added by 2.
print("Numpy array: ", numpy_array + 2)

# Subtraction in not possible in python_list. The following code will result in error
# print(python_list - 2)
# In order to all every element use a for loop
print("Python List: ")
for number in python_list:
  print(number - 2, end = " ")
print()
# Subtraction in numpy_array will make every element subtracted by 2.
print("Numpy array: ", numpy_array - 2)

# Division in not possible in python_list. The following code will result in error
# print(python_list / 2)
# In order to all every element use a for loop
print("Python List: ")
for number in python_list:
  print(number / 2, end = " ")
print()
# Division in numpy_array will make every element divided by 2.
print("Numpy array: ", numpy_array / 2)

# Taking power in not possible in python_list. The following code will result in error
# print(python_list ** 2)
# In order to all every element use a for loop
print("Python List: ")
for number in python_list:
  print(number ** 2, end = " ")
print()
# Taking power in numpy array will result in every element with its power.
print("Numpy array: ", numpy_array ** 2)

Python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array:  [ 2  4  6  8 10]
Python List: 
3 4 5 6 7 
Numpy array:  [3 4 5 6 7]
Python List: 
-1 0 1 2 3 
Numpy array:  [-1  0  1  2  3]
Python List: 
0.5 1.0 1.5 2.0 2.5 
Numpy array:  [0.5 1.  1.5 2.  2.5]
Python List: 
1 4 9 16 25 
Numpy array:  [ 1  4  9 16 25]


3. Time comparision

Numpy array are faster then normal python lists in creation and opeartion aswell

In [52]:
import timeit
import time

In [59]:
# Time in creation
numpy_array = timeit.timeit("[1, 2, 3, 4, 5]", number=1000000)
python_list = timeit.timeit("np.array([1, 2, 3, 4, 5])", setup="import numpy as np", number=1000000)
print(f"Numpy array: {numpy_array}, Python List: {python_list}")

# Time in operation in python arrays
python_list = [1, 2, 3, 4, 5]
start_time = time.time()
for number in python_list:
  number = number ** 2
total_time = time.time() - start_time
print("Total time for python list: ", total_time * 100000)

# Time in operation in numpy arrays
numpy_array = np.array([1, 2, 3, 4, 5])
start_time = time.time()
numpy_array = numpy_array ** 2
total_time = time.time() - start_time
print("Total time for numpy array: ", total_time * 100000)

Numpy array: 0.10163653000017803, Python List: 0.9114566520001972
Total time for python list:  9.083747863769531
Total time for numpy array:  6.961822509765625


# Creating multidimentional array in python

In [206]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array_2d)
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]
list4 = [16, 17, 18, 19, 20]
array_2d = np.array([list1, list2, list3, list4])
print(array_2d)

print(np.arange(5, 10)) # 5 se la kar 10 tak excluding 10 (9 taq)
print(np.linspace(1, 10, 3)) # 1 se lakr 10 taq 3 elements
print(np.zeros((5, 5))) # 5 x 5 array with all fill with zeros
print(np.full((5, 5), 34)) # 5 x 5 array with 34 element
print(np.eye(5, 6)) # 5 x 6 Identical array

arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr)) # simple sum
print(np.cumsum(arr)) # cumulative sum

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[5 6 7 8 9]
[ 1.   5.5 10. ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
15
[ 1  3  6 10 15]


#Array slicing

In [227]:
#2d
print("-"*5)
print("2D")
print("-"*5)
arr = np.array([[1, 2, 3], [6, 7, 8], [12, 12, 12], [3, 4, 76]])

print("All rows, Starting from all columns and then till last(but not inlcuded)")
print(arr[:, :-1]) #All rows, Starting from all columns and then till last(but not inlcuded)
print("All rows, Starting from second last column and then finishing till last")
print(arr[:, -2:]) #All rows, Starting from second last column and then finishing till last
print("0 till 2(not inlcuded) row and then all columns")
print(arr[0:2, :]) #0 till 2(not inlcuded) row and then all columns
print("0 till 3(not included) row and then 0 till 2 column(not included)")
print(arr[0:3, 0:2]) #0 till 3(not included) row and then 0 till 2 column(not included)

#3d
print("-"*5)
print("3D")
print("-"*5)
arr = np.array([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
])

print("All layers, Starting from second last row and then finishing till last, All column")
print(arr[:, -2:, :]) #All layers, Starting from second last row and then finishing till last, All column
print("All layers, Starting from all row and then till last(but not inlcuded), All column")
print(arr[:, :-1, :]) #All layers, Starting from all row and then till last(but not inlcuded), All column
print("0 till 3(not included) layers and then 0 till 2 row(not included), All column")
print(arr[0:3, 0:2, :]) #0 till 3(not included) layers and then 0 till 2 row(not included), All column
print("0 till 2(not inlcuded) layers and then all row, All column")
print(arr[0:2, :, :]) #0 till 2(not inlcuded) layers and then all row, All column
print("All layers, Starting from all row and then till last(but not inlcuded), column starting from third last till end")
print(arr[:, :-1, -3:]) #All layers, Starting from all row and then till last(but not inlcuded), column starting from third last till end
print("All layers, Starting from second last row and then finishing till last, column starting from 2 and then till end")
print(arr[:, -2:, 2:]) #All layers, Starting from second last row and then finishing till last, column starting from 2 and then till end
print("0 till 2(not inlcuded) layers and then all row, All starting columns and then till end excluding the last element")
print(arr[0:2, :, :-1]) #0 till 2(not inlcuded) layers and then all row, All starting columns and then till end excluding the last element
print("0 till 3(not included) layers and then 0 till 2 row(not included), all columns starting from 0 to 2(not included)")
print(arr[0:3, 0:2, 0:2]) #0 till 3(not included) layers and then 0 till 2 row(not included), all columns starting from 0 to 2(not included)

-----
2D
-----
All rows, Starting from all columns and then till last(but not inlcuded)
[[ 1  2]
 [ 6  7]
 [12 12]
 [ 3  4]]
All rows, Starting from second last column and then finishing till last
[[ 2  3]
 [ 7  8]
 [12 12]
 [ 4 76]]
0 till 2(not inlcuded) row and then all columns
[[1 2 3]
 [6 7 8]]
0 till 3(not included) row and then 0 till 2 column(not included)
[[ 1  2]
 [ 6  7]
 [12 12]]
-----
3D
-----
All layers, Starting from second last row and then finishing till last, All column
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
All layers, Starting from all row and then till last(but not inlcuded), All column
[[[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]]
0 till 3(not included) layers and then 0 till 2 row(not included), All column
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
0 till 2(not inlcuded) layers and then all row, All column

#Some built in functions on numpy array

In [93]:
brr = np.array([[1,2,3], [4,5,6]])
print(brr)
print(brr.ndim) # NUMBER OF DIMENTIONS
print(brr.shape) # ROWS , COLUMNS
print(brr.dtype) # ITEM SIZE 32 BIT OR 64 BIT OR ELSE
print(brr.itemsize) # ITEM SIZE IN BYTES(ONLY ONE)
print(brr.size) # SIZE OF ARRAY(NUMBER OF DIGITS OR CHARECTERS OR STRING TYPE OR ELSE)
print(brr.nbytes) # SUM OF NUMBER OF BYTES IN AN ARRAY

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
8
6
48


In [156]:
arr = np.array([1.93000, 2.3235, 3.15464, 25, 5])
print("Min :", np.min(arr))
print("Max :", np.max(arr))
print("Sin :", np.sin(arr))
print("Cos :", np.cos(arr))
print("Tan :", np.tan(arr))
print("Tanh :", np.tanh(arr))
print("Sinh :", np.sinh(arr))
print("Cosh :", np.cosh(arr))
print("Log :", np.log(arr)) # ln
print("Log10 :", np.log10(arr)) # log10
print("Exp :", np.exp(arr)) # e ^ every element
print("Floor :", np.floor(arr))
print("Ceil :", np.ceil(arr))
print("Trunc :", np.trunc(arr)) # remove decimal
print("Power :", np.power(arr, 2)) # arr elemt power 2
print("Square root :", np.sqrt(arr)) # square root
print("Mean :", np.mean(arr))
print("Medain :", np.median(arr))
# Generating random number between 0 and 11
random_number = np.random.randint(0, 11)
print("Random number generated is: ", random_number)

Min : 1.93
Max : 25.0
Sin : [ 0.93617705  0.72984327 -0.01304698 -0.13235175 -0.95892427]
Cos : [-0.35152884 -0.68361451 -0.99991488  0.99120281  0.28366219]
Tan : [-2.66315858 -1.06762401  0.01304809 -0.13352641 -3.38051501]
Tanh : [0.95873341 0.98100154 0.99636792 1.         0.9999092 ]
Sinh : [3.37218102e+00 5.05671067e+00 1.17009709e+01 3.60024497e+10
 7.42032106e+01]
Cosh : [3.51732922e+00 5.15464090e+00 1.17436246e+01 3.60024497e+10
 7.42099485e+01]
Log : [0.65752    0.84307467 1.14887438 3.21887582 1.60943791]
Log10 : [0.28555731 0.36614268 0.49894981 1.39794001 0.69897   ]
Exp : [6.88951024e+00 1.02113516e+01 2.34445955e+01 7.20048993e+10
 1.48413159e+02]
Floor : [ 1.  2.  3. 25.  5.]
Ceil : [ 2.  3.  4. 25.  5.]
Trunc : [ 1.  2.  3. 25.  5.]
Power : [  3.7249       5.39865225   9.95175353 625.          25.        ]
Square root : [1.3892444  1.52430312 1.77613063 5.         2.23606798]
Mean : 7.481628000000001
Medain : 3.15464
Random number generated is:  6


# Sample project 1

# Weather Data Analyzer
Scenario: You are a data analyst for a small weather station. You've collected daily temperature data (in Celsius) for one week from seven different cities. Your task is to process and analyze this data.

Convert to NumPy Array: Load the data into a NumPy array to begin your analysis.

Overall Statistics: Calculate the overall average, maximum, and minimum temperature for the entire dataset.

City Analysis: For each city (column), find:

Its average weekly temperature.

The day it experienced its highest temperature.

Day Analysis: For each day (row), find:

The average temperature across all cities.

The city with the highest temperature that day.

Find Anomalies: Identify any days where a city's temperature was more than 5 degrees above the overall average temperature for that specific city.

Convert to Fahrenheit: The data needs to be sent to a US-based team. Create a new array with all temperatures converted to Fahrenheit.

In [141]:
#[city1, city2, city3, city4, city5, city6, city7]
weekly_temps = [
    [22, 25, 32, 31, 18, 27, 21], # day1
    [24, 26, 21, 29, 19, 25, 23], # day2
    [23, 27, 20, 29, 17, 28, 22], # day3
    [25, 28, 22, 30, 20, 26, 24], # day4
    [21, 24, 18, 28, 16, 24, 20]  # day5
]


In [142]:
numpy_array = np.array(weekly_temps)
print("Overall minimum temperature: ", np.min(numpy_array))
print("Overall maximum temperature: ", np.max(numpy_array))
print("Overall average temperature: ", np.mean(numpy_array))

Overall minimum temperature:  16
Overall maximum temperature:  32
Overall average temperature:  23.857142857142858


In [143]:
print("Average city temperature by week")
print(np.mean(numpy_array, axis=0)) # Axis = 0 means columns
print("The day they experienced the highest temperature")
print(np.argmax(numpy_array, axis=0)) # Axis = 1 means row

Average city temperature by week
[23.  26.  22.6 29.4 18.  26.  22. ]
The day they experienced the highest temperature
[3 3 0 0 3 2 3]


In [144]:
print("Average temperature by day")
print(np.mean(numpy_array, axis=1))
print("The city with the highest temperature that day")
print(np.argmax(numpy_array, axis=1))

Average temperature by day
[25.14285714 23.85714286 23.71428571 25.         21.57142857]
The city with the highest temperature that day
[2 3 3 3 3]


In [148]:
current_day = 1
days = []
day_found = False
for day_temp in numpy_array:
  print("Average temperature of the day is: ", np.mean(day_temp))
  for temp in day_temp:
    if temp > (np.mean(day_temp) + 5):
      day_found = True
      days.append(current_day)
      current_day += 1
      break
  if day_found:
    day_found = False
  else:
    current_day += 1
print("Days with temperature more then 5 degrees then average are: ", days)

Average temperature of the day is:  25.142857142857142
Average temperature of the day is:  23.857142857142858
Average temperature of the day is:  23.714285714285715
Average temperature of the day is:  25.0
Average temperature of the day is:  21.571428571428573
Days with temperature more then 5 degrees then average are:  [1, 2, 3, 5]


In [149]:
def convert_temperature_into_farenheight(temperatures):
  return (temperatures * 9/5) + 32

In [151]:
print(convert_temperature_into_farenheight(numpy_array))

[[71.6 77.  89.6 87.8 64.4 80.6 69.8]
 [75.2 78.8 69.8 84.2 66.2 77.  73.4]
 [73.4 80.6 68.  84.2 62.6 82.4 71.6]
 [77.  82.4 71.6 86.  68.  78.8 75.2]
 [69.8 75.2 64.4 82.4 60.8 75.2 68. ]]


#Sample project 2

Project: Student Gradebook Analyzer
Scenario: You're a teacher with a gradebook for your class. You need to analyze student performance across multiple subjects and assignments.

Your raw data is a 2D NumPy array where:

Each row represents a student

Each column represents a subject (Math, Science, English, History)

Calculate Overall Statistics: Find the class average, highest score, and lowest score across all subjects.

Subject Analysis: For each subject, calculate the average, highest, and lowest score.

Student Performance: For each student, calculate their average grade across all subjects.

Find Top Performers: Identify which student has the highest average grade.

Pass/Fail Analysis: Count how many students passed each subject (passing grade ≥ 70).

Grade Adjustment: Add 5 points to every Math grade (but don't let any score exceed 100).

Find Consistency: Calculate the standard deviation for each student (how consistent their grades are across subjects).

In [194]:
# Subjects: [Math, Science, English, History]
grades = np.array([
    [85, 92, 78, 88],  # Student 0
    [67, 75, 82, 79],  # Student 1
    [91, 89, 93, 87],  # Student 2
    [55, 62, 70, 68],  # Student 3
    [78, 85, 80, 84]   # Student 4
])

In [195]:
# Calculate Overall Statistics: Find the class average, highest score, and lowest score across all subjects.
print("Class average: ", np.mean(grades))
print("Class highest score: ", np.max(grades))
print("Class lowest score: ", np.min(grades))

Class average:  79.4
Class highest score:  93
Class lowest score:  55


In [197]:
# Subject Analysis: For each subject, calculate the average, highest, and lowest score
print("Average of each subject: ", np.mean(grades, axis=0))
print("Maximum of each subject: ", np.max(grades, axis=0))
print("Minimum of each subject: ", np.min(grades, axis=0))

Average of each subject:  [75.2 80.6 80.6 81.2]
Maximum of each subject:  [91 92 93 88]
Minimum of each subject:  [55 62 70 68]


In [198]:
# Student Performance: For each student, calculate their average grade across all subjects.
print("Average of each student: ", np.mean(grades, axis=1))
print("Maximum of each student: ", np.max(grades, axis=1))
print("Minimum of each student: ", np.min(grades, axis=1))


Average of each student:  [85.75 75.75 90.   63.75 81.75]
Maximum of each student:  [92 82 93 70 85]
Minimum of each student:  [78 67 87 55 78]


In [199]:
# Find Top Performers: Identify which student has the highest average grade.
print("Student with highest average grade: ", np.argmax(np.mean(grades, axis=1)))

Student with highest average grade:  2


In [201]:
# Pass/Fail Analysis: Count how many students passed each subject (passing grade ≥ 70).
print("Number of students passed each subject: ", np.sum(grades >= 70, axis=0))
#first element is subject1, second element is subject2, third element is subject3 and so in

Number of students passed each subject:  [3 4 5 4]


In [202]:
# Grade Adjustment: Add 5 points to every Math grade (but don't let any score exceed 100).
for student in grades:
  if student[0] < 100:
    student[0] += 5
print(grades)

[[90 92 78 88]
 [72 75 82 79]
 [96 89 93 87]
 [60 62 70 68]
 [83 85 80 84]]


In [205]:
# Find Consistency: Calculate the standard deviation for each student (how consistent their grades are across subjects).
print("Standard deviation of each student: ", np.std(grades, axis=1))

Standard deviation of each student:  [5.38516481 3.80788655 3.49106001 4.12310563 1.87082869]


In [232]:
arr = np.array([1, 2, 3, 4, 5])
brr = np.array([6, 7, 8, 9, 10])

print(np.hstack((arr, brr)))
print(np.vstack((arr, brr)))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
