In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
print(arr.ndim)

1


In [9]:
brr = np.array([[1,2,3], [4,5,6]])
print(brr)
print(brr.ndim) # NUMBER OF DIMENTIONS 
print(brr.shape) # ROWS , COLUMNS 
print(brr.dtype) # ITEM SIZE 32 BIT OR 64 BIT OR ELSE 
print(brr.itemsize) # ITEM SIZE IN BYTES(ONLY ONE)
print(brr.size) # SIZE OF ARRAY(NUMBER OF DIGITS OR CHARECTERS OR STRING TYPE OR ELSE)
print(brr.nbytes) # SUM OF NUMBER OF BYTES IN AN ARRAY

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
4
6
24


In [10]:
arr = np.array([[1,2,3], [4,5,6]], dtype = 'int64') # CAHNGING NUMBER OF BYTES
print(arr.itemsize)

8


In [23]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr[1,4]) # ROW NUMBER 1 COLUMN NUMBER 4
print(arr[1,0:7]) # ROW NUMBER 1 COLUMN NUMBER 0 TILL 7
print(arr[0,:]) # PRINTING A SPECIFIC ROW(0 ROW ALL COLUMNS)
print(arr[:,1]) # PRINTING A SPECIFIC COLUMN(ALL ROWS 1 COLUMN)

12
[ 8  9 10 11 12 13 14]
[1 2 3 4 5 6 7]
[2 9]


In [29]:
#[STARTING INDEX : ENDING INDEX : JUMP SIZE]
arr = np.array([[1,2,3,4,10,11,12], [5,6,7,8,22,33,44]])
print(arr)
print(arr[0,0:7:2]) # ZERO ROW COLUMN STARTING FROM 0 ENDING at 3  WITH A JUMP OF 2


[[ 1  2  3  4 10 11 12]
 [ 5  6  7  8 22 33 44]]
[ 1  3 10 12]


In [30]:
arr = np.zeros(5) # CREATES 5 ROWS
brr = np.zeros((2,2)) # CREATES 2 ROWS 2 COLUMNS
print(arr)
print(brr)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [31]:
arr = np.ones(5) # CREATES 5 ROWS
brr = np.ones((2,2)) # CREATES 2 ROWS 2 COLUMNS
print(arr)
print(brr)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [33]:
# arr = np.full(5) WILL RESULT INTO AN ERROR
brr = np.full((2,2), 5) # 2 BY 2 MATRIX WITH VALUE 5 IN THEM 
print(arr)
print(brr)

[1. 1. 1. 1. 1.]
[[5 5]
 [5 5]]


In [36]:
arr = np.eye(2,3) # DIAGNAL ALL ONE
print(arr)
brr = np.eye(5,5)
print()
print()
print(brr)

[[1. 0. 0.]
 [0. 1. 0.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
a = np.array([1,2,3,4])
print(a + 2) # ARRAY ELEMENTS + 2
print(a - 2) # ARRAY ELEMENTS - 2
print(a * 2) # ARRAY ELEMENTS * 2
print(a / 2) # ARRAY ELEMENTS / 2

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [40]:
# THERE IS NO SUCH THING AS PRE AND POST INCREMENT IN PYTHON
arr = np.array([4,5,1,2,3])
print(++arr)
# print(arr++) WILL RESULT INTO AN ERROR 
print()
print()
# CORRECT WAY
arr = arr + 2 # OR  arr =+ 2
print(arr)

[4 5 1 2 3]


[6 7 3 4 5]


In [41]:
arr = np.array([1,2,34,5,321,6,4523,12.3])
print(np.sin(a)) # PRINTS SIN
print(np.cos(a)) # PRINTS COS 
print(np.tan(a)) # PRINTS TAN

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [44]:
# ALWAYS USE COPY FUNCTION
arr = [1,2,3,4]
brr = arr.copy()
print(brr)
arr[1]  = 200
print(arr[1])
print(brr[1])

[1, 2, 3, 4]
200
2


In [45]:
# CHANGING NUMBER OF DIMENTIONS

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
newArray = arr.reshape(2,2,-1)
print(newArray)
newArray = arr.reshape(-1)
print(newArray)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
# CONCATENATE 2 ARRAYS
arr = np.array([1,2,3,4,5])
brr = np.array([6,7,8,9,10])
print(arr+brr) # ADDS CORRESPONDING INDEXES
crr = np.concatenate((arr, brr))
print(crr)

[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]
